### ISSUE TITLE
Good Product vs. Good Engineering

### ISSUE THREAD

**Issue by groundwater** [NodeOS/node-npkg#3]
I think `npkg` does too many things, right now it includes:
1. installing global modules
2. configuring modules
3. running modules in the foreground
4. daemonizing modules with init via an http interface

Especially for a node module, this is too many things. However, I think from a newbie to node-os perspective, it's gonna be a PITA the remember a bunch of random commands to do basic system operations.

I propose the following:
1. create smaller modules that export their functionality via `module.exports`, or via a `bin` key in their `package.json` file.
2. _wire_ them all together under `npkg` or another _easy to remember_ module, and export all the functionality as sub-commands.

Typing `npkg` without any commands will just display all possible commands to use. Any incomplete command usage should prompt the user to explain how to run each command. The `npkg` command should be as self-learning as possible.

@EndangeredMassa

**Comment by EndangeredMassa** [comment]
Agreed, although I think it's fine as two separate sub-modules.

The names could be better, but something like:
- `os`: central command that uses subcommands to access `npkg` and `service`
- `npkg`: install, uninstall, and list packages
- `service`: start, stop, list, status, and configure services

`run` (in the foreground) should probably go in `service` as well.

**Comment by piranna** [comment]
If NPM would have a `-u` parameter to install packages globally for a particular user (as currently NodeOS does) npkg would remove that functionality at all.

I like the `service` name for the package/tool to manage the daemons live cycle.

**Comment by piranna** [comment]
After reading the source code, I would move the `service` utility to the https://github.com/NodeOS/node-init package and export both `init` and `service` commands, since they are so much related between them (ona manager of daemon, other the user interface).

As a side note, I would like to search for other communication methods, the HTTP server is a nice trick, but open the doors to security holes since you could access to it from other machines (is it intended? is it desirable?). I have been thinking about other alternatives like [postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window.postMessage) inter-window communications (could be seen as somewhat similar to InterProcess Communications in the NodeOS contest), but there's no implementation for Node.js.

**Comment by groundwater** [comment]
@piranna I think I agree with you on merging `init` and `npkg`. They are so intimately related, that it makes sense to install them together. 

Keep in mind that `npkg` is a **product**. It is there to provide people with as easy an experience as possible. What we probably want is a solid _technology_ underneath that is highly modular, and extensible which `npkg` uses.

We should discuss the _technology_ side and _product_ side separately. I absolutely agree that we should separate the technology side as much as possible, but I want the end-user of the product to only need to remember one command at first, namely `npkg`.

> I have been thinking about other alternatives like postMessage() inter-window communications

The `postMessage` function is a browser-specific thing that doesn't apply to node.

> I would like to search for other communication methods, the HTTP server is a nice trick, but open the doors to security holes since you could access to it from other machines

HTTP is perfectly safe, and used by projects like Docker. There are various ways to secure it. By default, node-os only binds to the loopback devices, so it's only accessible from the local machine. You can restrict it to a single user by using unix sockets, which are just as secure as any other IPC method.

**Comment by piranna** [comment]
That's why I proposed to use https://github.com/nodejitsu/forever-monitor as substitute of `init` and https://github.com/nodejitsu/forever as substitute of `service`, their functionality and focus is somewhat similar and work in a similar way according to their code, and they are more tested. They have a lot more dependencies and are not so minimalist, though...

Once splitted `npkg` removed its relationship with `init`, it became just a proxy command to `npm`, so I don't think is still necesary since it only install packages on the user $HOME instead of `/`, something that can be achieved with `npm` using environment variables, and people don't need to learn a new tool :-) There's a problem with NodeOS specific packages, but that can be fixed with a proxy repository as is being used right now. It would be better if `npm` would work with several repositories as `APT` does, but maybe it's not done this way for a reason or security... :-/

I know `postMessage()` is browser-specific, but It was just an example, it's only that the HTTP server was a strange thing to me, although an interesting idea to communicate with the process that could be standarized and extended to be used for other things (something like the control files in Plan9). Forever has also an optional [web interface](https://github.com/FGRibreau/forever-webui) to manage the process, so maybe control the services from an external machine was not so bad idea as I though in a first time... :-)

**Comment by groundwater** [comment]
I tried to document the design decisions of init a little in NodeOS/node-init#3.

**Comment by EndangeredMassa** [comment]
Should this issue be closed?

**Comment by piranna** [comment]
why you think so?

**Comment by EndangeredMassa** [comment]
It was just pretty old. No worries.

**Comment by piranna** [comment]
Yes, it can be closed, in the current NodeOS architecture npkg is deprecated in benefict of forever, npm & ndm.
